# Generated by Django 2.0 on 2017-12-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
