# Generated by Django 2.0 on 2017-12-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddict', '0003_auto_20171225_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='friq',
            new_name='freq',
        ),
    ]
