# Generated by Django 2.0 on 2018-02-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddict', '0006_auto_20171225_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ('-freq',)},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-freq',)},
        ),
        migrations.AlterField(
            model_name='word',
            name='freq',
            field=models.FloatField(db_index=True, null=True, verbose_name='Friquency'),
        ),
    ]
